"""PostgreSQL DDL for the SQL-MCP medical-billing business schema.

RAG/document tables stay in ``public``. SQL-MCP tables live in ``business``.
"""

from __future__ import annotations

DEFAULT_SCHEMA = "business"

BUSINESS_TABLES = (
    "customers",
    "billing_accounts",
    "claims",
    "invoices",
    "payments",
    "claim_adjustments",
    "tickets",
    "ticket_comments",
)

# Parent-before-child for inserts; reverse for drops.
INSERT_ORDER = BUSINESS_TABLES
PK_COLUMNS = {
    "customers": "customer_id",
    "billing_accounts": "billing_account_id",
    "claims": "claim_id",
    "invoices": "invoice_id",
    "payments": "payment_id",
    "claim_adjustments": "adjustment_id",
    "tickets": "ticket_id",
    "ticket_comments": "comment_id",
}


def schema_ddl(schema: str = DEFAULT_SCHEMA) -> str:
    s = _ident(schema)
    return f"""
CREATE SCHEMA IF NOT EXISTS {s};

CREATE TABLE IF NOT EXISTS {s}.customers (
  customer_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_number VARCHAR(30) UNIQUE NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  billing_address VARCHAR(500),
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS {s}.billing_accounts (
  billing_account_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id INTEGER NOT NULL REFERENCES {s}.customers(customer_id),
  account_status VARCHAR(30) NOT NULL,
  insurance_provider VARCHAR(150),
  insurance_member_id VARCHAR(100),
  outstanding_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  last_statement_date DATE,
  next_due_date DATE,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS {s}.claims (
  claim_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  billing_account_id INTEGER NOT NULL REFERENCES {s}.billing_accounts(billing_account_id),
  claim_number VARCHAR(50) UNIQUE NOT NULL,
  service_date DATE NOT NULL,
  provider_name VARCHAR(200) NOT NULL,
  procedure_code VARCHAR(30) NOT NULL,
  billed_amount NUMERIC(12,2) NOT NULL,
  allowed_amount NUMERIC(12,2),
  insurance_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  patient_responsibility NUMERIC(12,2) NOT NULL DEFAULT 0,
  claim_status VARCHAR(40) NOT NULL,
  denial_reason VARCHAR(500),
  submitted_at TIMESTAMP,
  processed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS {s}.invoices (
  invoice_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  billing_account_id INTEGER NOT NULL REFERENCES {s}.billing_accounts(billing_account_id),
  invoice_number VARCHAR(50) UNIQUE NOT NULL,
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  total_amount NUMERIC(12,2) NOT NULL,
  amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount_due NUMERIC(12,2) NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS {s}.payments (
  payment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  billing_account_id INTEGER NOT NULL REFERENCES {s}.billing_accounts(billing_account_id),
  invoice_id INTEGER REFERENCES {s}.invoices(invoice_id),
  payment_reference VARCHAR(100) UNIQUE NOT NULL,
  payment_date DATE,
  amount NUMERIC(12,2) NOT NULL,
  payment_method VARCHAR(50),
  status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS {s}.claim_adjustments (
  adjustment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  claim_id INTEGER NOT NULL REFERENCES {s}.claims(claim_id),
  adjustment_code VARCHAR(50) NOT NULL,
  adjustment_reason VARCHAR(500) NOT NULL,
  adjustment_amount NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS {s}.tickets (
  ticket_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_number VARCHAR(50) UNIQUE NOT NULL,
  customer_id INTEGER NOT NULL REFERENCES {s}.customers(customer_id),
  category VARCHAR(50) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(20) NOT NULL,
  status VARCHAR(30) NOT NULL,
  assigned_team VARCHAR(100),
  assigned_agent VARCHAR(100),
  resolution TEXT,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  closed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS {s}.ticket_comments (
  comment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id INTEGER NOT NULL REFERENCES {s}.tickets(ticket_id),
  author_type VARCHAR(30) NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  "comment" TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_billing_accounts_customer_id
  ON {s}.billing_accounts(customer_id);
CREATE INDEX IF NOT EXISTS idx_claims_billing_account_id
  ON {s}.claims(billing_account_id);
CREATE INDEX IF NOT EXISTS idx_invoices_billing_account_id
  ON {s}.invoices(billing_account_id);
CREATE INDEX IF NOT EXISTS idx_payments_billing_account_id
  ON {s}.payments(billing_account_id);
CREATE INDEX IF NOT EXISTS idx_payments_invoice_id
  ON {s}.payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_claim_adjustments_claim_id
  ON {s}.claim_adjustments(claim_id);
CREATE INDEX IF NOT EXISTS idx_tickets_customer_id
  ON {s}.tickets(customer_id);
CREATE INDEX IF NOT EXISTS idx_ticket_comments_ticket_id
  ON {s}.ticket_comments(ticket_id);
"""


def rag_schema_ddl() -> str:
    """Idempotent public-schema tables used by document RAG (no pgvector required)."""
    return """
CREATE TABLE IF NOT EXISTS documents (
  id VARCHAR(100) PRIMARY KEY,
  workspace_id VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  file_type VARCHAR(50) NOT NULL,
  storage_path VARCHAR(512) NOT NULL,
  status VARCHAR(50) NOT NULL,
  error TEXT,
  size INT NOT NULL,
  uploaded_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS document_chunks (
  id VARCHAR(100) PRIMARY KEY,
  workspace_id VARCHAR(100) NOT NULL,
  document_id VARCHAR(100) REFERENCES documents(id) ON DELETE CASCADE,
  document_name VARCHAR(255) NOT NULL,
  section_path TEXT[] DEFAULT '{}',
  chunk_index INT NOT NULL,
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  embedding TEXT
);

CREATE INDEX IF NOT EXISTS idx_documents_workspace_id ON documents(workspace_id);
CREATE INDEX IF NOT EXISTS idx_chunks_workspace_doc ON document_chunks(workspace_id, document_id);
"""


def _ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'
